---
- import_tasks: validate.yml

- name: "build a temporary directory for fragments"
  tempfile:
    state: directory
  register: tmpdir

- set_fact:
    tmpdir: "{{ tmpdir.path }}"

- include_tasks: subtasks/header.yml

- include_tasks: subtasks/modules.yml
  when: "vhost_modules is defined"

- include_tasks: subtasks/ssl.yml
  when: "vhost_ssl"

- include_tasks: subtasks/serverinfo.yml

- include_tasks: subtasks/urlaliases.yml
  when: "vhost_urlaliases is defined"

- include_tasks: subtasks/extracfg.yml
  when: "vhost_type == 'wsgi' or vhost_extra_configs is defined"

- include_tasks: subtasks/directories.yml
  when: "vhost_directories is defined"

- include_tasks: subtasks/locations.yml
  when: "vhost_locations is defined"

- include_tasks: subtasks/logging.yml

- include_tasks: subtasks/footer.yml

- name: "assemble the configuration file"
  assemble:
    src: "{{ tmpdir }}"
    remote_src: true
    dest: "{{ tmpdir }}/assembled"
    regexp: "\\d*-.*"

- name: "copy and validate the configuration file"
  copy:
    src: "{{ tmpdir }}/assembled"
    remote_src: true
    dest: "{{ apache_confd_dir }}/{{ vhost_index }}-{{ vhost_name }}.conf"
    owner: root
    group: root
    mode: 0755
    validate: "/usr/sbin/httpd -S -C '# %s'"
  become: true
  notify:
    - restart apache

- name: "remove the temporary directory"
  file:
    path: "{{ tmpdir }}"
    state: absent

