---
- set_fact:
    vhost_ip: "*"
  when: "vhost_ip is not defined"

- set_fact:
    vhost_port: 80
  when: "vhost_port is not defined"

- set_fact:
    vhost_name: default
  when: "vhost_name is not defined"

- name: "validate vhost_port"
  assert:
    that:
      - "vhost_port is defined"
      - "vhost_port is number"
    msg: "'vhost_post' must be defined and a number"

- name: "validate vhost_admin"
  assert:
    that:
      - "'@' in vhost_admin"
      - "'.' in vhost_admin"
    msg: "'vhost_admin' must be an email address when defined"
  when: "vhost_admin is defined"

- name: "validate vhost_name"
  assert:
    that:
      - "vhost_name is defined"
      - "'.' in vhost_name or vhost_name == 'default'"
    msg: "'vhost_name' must be defined and a domain name"

- block:
  - name: "validate vhost_aliases is a list"
    assert:
      that: "vhost_aliases is iterable and vhost_aliases is not string"

  - name: "validate each vhost_alias is a domain"
    assert:
      that:
        - "'{{ item }}' is string"
        - "'.' in '{{ item }}'"
      msg: "'{{ item }}' must be a domain name"
    with_items: "{{ vhost_aliases }}"
  when: "vhost_aliases is defined"

- name: "validate vhost_type"
  assert:
    that:
      - "vhost_type is defined"
      - "vhost_type|lower in ['static', 'wsgi', 'redirect']"
    msg: "'vhost_type' must be 'static', 'wsgi', or 'redirect'"

- include_tasks: "validations/type_{{ vhost_type }}.yml"
  when: "vhost_type != 'static'"

- block:
    - name: "validate vhost_docroot"
      assert:
        that:
          - "vhost_docroot is defined"
          - "vhost_docroot is abs"
        msg: "'vhost_docroot' must exist be an absolute path"

    - name: "ensure vhost_docroot exists"
      stat:
        path: "{{ vhost_docroot }}"
      register: vdt

    - fail:
        msg: "'vhost_docroot' must exist if not using a wildcard"
      when: "'*' not in vhost_docroot and not vdt.stat.exists"
  when: "vhost_type != 'redirect'"

- set_fact:
    vhost_ssl: false
  when: "vhost_ssl is not defined"

- include_tasks: validations/ssl.yml
  when: "vhost_ssl"

- include_tasks: validations/modules.yml
  when: "vhost_modules is defined"

- include_tasks: validations/urlaliases.yml
  when: "vhost_urlaliases is defined"

- include_tasks: validations/locations.yml
  when: "vhost_locations is defined"

# Always included for real sites because at least 'vhost_docroot' will be added.
- include_tasks: validations/directories.yml
  when: "vhost_type != 'redirect'"

- name: "validate apache_log_dir"
  stat:
    path: "{{ apache_log_dir }}"
  register: ald

- fail:
    msg: "'apache_log_dir' must exist"
  when: "not ald.stat.exists"

- name: "validate apache_confd_dir"
  stat:
    path: "{{ apache_confd_dir }}"
  register: acd

- fail:
    msg: "'apache_confd_dir' must exist"
  when: "not acd.stat.exists"

- include_tasks: validations/extracfg.yml
  when: "vhost_extra_configs is defined"
