---
- name: "validate vhost_sslcert"
  assert:
    that:
      - "vhost_sslcert is defined"
      - "vhost_sslcert is exists"
    msg: "'vhost_sslcert' must be defined and exist"

- name: "validate vhost_sslcertkey"
  assert:
    that:
      - "vhost_sslcertkey is defined"
      - "vhost_sslcertkey is exists"
    msg: "'vhost_sslcertkey' must be defined and exist"
