---
- name: "ensure wsgi_module is loaded"
  set_fact:
    vhost_modules: >
      {{ vhost_modules|default([]) }} + 
      [{'module': 'wsgi_module', 'filename': 'lib64/httpd/modules/mod_wsgi.so'}]

- name: "set vhost_wsgi_name"
  set_fact:
    vhost_wsgi_name: "{{ vhost_name }}"
  when: "vhost_wsgi_name is not defined"

- name: "set vhost_wsgi_procs"
  set_fact:
    vhost_wsgi_procs: "{{ wsgi_proc_count }}"
  when: "vhost_wsgi_procs is not defined"

- name: "validate vhost_wsgi_threads"
  assert:
    that: "vhost_wsgi_threads is number"
  when: "vhost_wsgi_threads is defined"

- name: "locate vhost_wsgi_home"
  set_fact:
    vhost_wsgi_home: "{{ lookup('first_found', paths) }}"
  vars:
    paths:
      - "{{ vhost_wsgi_home|default(omit) }}"
      - "{{ vhost_docroot }}/{{ vhost_wsgi_home|default(omit) }}"
      - "{{ vhost_docroot }}"

- name: "validate vhost_wsgi_home"
  assert:
    that: "vhost_wsgi_home is directory"
  when: "vhost_wsgi_home is defined"

- name: "set vhost_wsgi_lang"
  set_fact:
    vhost_wsgi_lang: "{{ wsgi_language }}"
  when: "vhost_wsgi_lang is not defined"


- name: "locate vhost_wsgi_pythonhome"
  set_fact:
    vhost_wsgi_pythonhome: "{{ lookup('first_found', paths) }}"
  vars:
    paths:
      - "{{ vhost_wsgi_pythonhome }}"
      - "{{ vhost_wsgi_home|default(omit) }}/{{ vhost_wsgi_pythonhome }}"
      - "{{ vhost_docroot }}/{{ vhost_wsgi_pythonhome }}"
  when: "vhost_wsgi_pythonhome is defined"

- name: "validate vhost_wsgi_pythonhome"
  assert:
    that:
      - "vhost_wsgi_pythonhome is directory"
      - "'{{ vhost_wsgi_pythonhome }}/bin/python' is file"
    msg: "'{{ vhost_wsgi_pythonhome }}' must be a directory with 'bin/python' available."
  when: "vhost_wsgi_pythonhome is defined"

- name: "validate vhost_wsgi_scriptaliases is a list"
  assert:
    that: 'vhost_wsgi_scriptaliases is iterable and vhost_wsgi_scriptaliases is not string'

- name: "vhost_directories is empty mapping"
  set_fact:
    vhost_directories: {}
  when: "vhost_directories is not defined"

- name: "vhost_wsgi_absaliases is empty mapping"
  set_fact:
    vhost_wsgi_absaliases: []

- include_tasks: validations/wsgi_scriptaliases.yml
  with_items: "{{ vhost_wsgi_scriptaliases }}"
