---
- name: "ensure wsgi_module is loaded"
  set_fact:
    vhost_modules: >
      {{ vhost_modules|default([]) }} + 
      [{'module': 'wsgi_module', 'filename': 'lib64/httpd/modules/mod_wsgi.so'}]

- name: "set vhost_wsgi_name"
  set_fact:
    vhost_wsgi_name: "{{ vhost_name }}"
  when: "vhost_wsgi_name is not defined"

- name: "set vhost_wsgi_procs"
  set_fact:
    vhost_wsgi_procs: "{{ wsgi_proc_count }}"
  when: "vhost_wsgi_procs is not defined"

- name: "validate vhost_wsgi_threads"
  assert:
    that: "vhost_wsgi_threads is number"
  when: "vhost_wsgi_threads is defined"

- name: "locate vhost_wsgi_home"
  set_fact:
    vhost_wsgi_home: "{{ lookup('first_found', paths) }}"
  vars:
    paths:
      - "{{ vhost_wsgi_home|default(omit) }}"
      - "{{ vhost_docroot }}/{{ vhost_wsgi_home|default(omit) }}"
      - "{{ vhost_docroot }}"

- name: "validate vhost_wsgi_home"
  stat:
    path: "{{ vhost_wsgi_home }}"
  register: vwh
  when: "vhost_wsgi_home is defined"

- fail:
    msg: "'vhost_wsgi_home' must exist"
  when: "vhost_wsgi_home is defined and not vwh.stat.exists"

- name: "set vhost_wsgi_lang"
  set_fact:
    vhost_wsgi_lang: "{{ wsgi_language }}"
  when: "vhost_wsgi_lang is not defined"

- name: "locate vhost_wsgi_pythonhome"
  set_fact:
    vhost_wsgi_pythonhome: "{{ lookup('first_found', paths) }}"
  vars:
    paths:
      - "{{ vhost_wsgi_pythonhome }}"
      - "{{ vhost_wsgi_home|default(omit) }}/{{ vhost_wsgi_pythonhome }}"
      - "{{ vhost_docroot }}/{{ vhost_wsgi_pythonhome }}"
  when: "vhost_wsgi_pythonhome is defined"

- name: "validate vhost_wsgi_pythonhome"
  stat:
    path: "{{ vhost_wsgi_pythonhome }}"
  register: vwph
  when: "vhost_wsgi_pythonhome is defined"

- fail:
    msg: "'vhost_wsgi_pythonhome' must be a directory"
  when: "vhost_wsgi_pythonhome is defined and not vwph.stat.isdir"

- name: "validate vhost_wsgi_pythonhome has Python executable"
  stat:
    path: "{{ vhost_wsgi_pythonhome }}/bin/python"
  register: vwphp

- fail:
    msg: "'{{ vhost_wsgi_pythonhome }}' must be a directory with 'bin/python' available."
  when: "vhost_wsgi_pythonhome is defined and not vwphp.stat.executable"

- name: "validate vhost_wsgi_scriptaliases is a list"
  assert:
    that: 'vhost_wsgi_scriptaliases is iterable and vhost_wsgi_scriptaliases is not string'

- name: "vhost_directories is empty mapping"
  set_fact:
    vhost_directories: {}
  when: "vhost_directories is not defined"

- name: "vhost_wsgi_absaliases is empty mapping"
  set_fact:
    vhost_wsgi_absaliases: []

- include_tasks: validations/wsgi_scriptaliases.yml
  with_items: "{{ vhost_wsgi_scriptaliases }}"
